/* Generated By:JavaCC: Do not edit this line. TinyParserConstants.java */
package parser_javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TinyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letter = 1;
  /** RegularExpression Id. */
  int dig = 2;
  /** RegularExpression Id. */
  int sign = 3;
  /** RegularExpression Id. */
  int pdec = 4;
  /** RegularExpression Id. */
  int pexp = 5;
  /** RegularExpression Id. */
  int bool = 7;
  /** RegularExpression Id. */
  int num = 8;
  /** RegularExpression Id. */
  int t = 9;
  /** RegularExpression Id. */
  int f = 10;
  /** RegularExpression Id. */
  int and = 11;
  /** RegularExpression Id. */
  int or = 12;
  /** RegularExpression Id. */
  int not = 13;
  /** RegularExpression Id. */
  int id = 14;
  /** RegularExpression Id. */
  int lent = 15;
  /** RegularExpression Id. */
  int ldec = 16;
  /** RegularExpression Id. */
  int lexp = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letter>",
    "<dig>",
    "<sign>",
    "<pdec>",
    "<pexp>",
    "<token of kind 6>",
    "\"bool\"",
    "\"num\"",
    "\"true\"",
    "\"false\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "<id>",
    "<lent>",
    "<ldec>",
    "<lexp>",
    "\"&&\"",
    "\";\"",
    "\"=\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"==\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"!=\"",
    "\"*\"",
    "\"/\"",
  };

}
